--  TABLAS
CREATE TABLE COTIZANTE
(numeroCT       NUMBER(7,0)     NOT NULL,
 rutCT          CHAR(9)         NOT NULL,
 apellido1CT    VARCHAR2(15)    NOT NULL,
 apellido2CT    VARCHAR2(15)    NOT NULL,
 nombresCT      VARCHAR2(30)    NOT NULL,
 fechaNacCT     DATE            NOT NULL,
 generoCT       CHAR(1)         NOT NULL,
 codigoAFP      NUMBER(4,0)     NOT NULL,
 ahorroObligCT  NUMBER(9,0)     NOT NULL,   -- corresponde al monto total de las cotizaciones obligatorias
 ahorroVolunCT  NUMBER(9,0)     NOT NULL,   -- corresponde al monto total de las cotizaciones voluntarias
 tipoCT         CHAR(1)         NOT NULL,
 tipoContratoCT CHAR(2)         NOT NULL,
 codigoCM       NUMBER(5,0)     NOT NULL
);

CREATE TABLE INVERSION
(codigoIN       NUMBER(10,0)    NOT NULL,   --  corresponde al código de la inversión
 numeroIN       number(1,0)     not null,   --  corresponde al número de inversión, iniciando en 1, según en cuántos fondos se invierta
 numeroCT       NUMBER(7,0)     NOT NULL,
 fechaIN        DATE            NOT NULL,
 tipoFondoIN    CHAR(1)         NOT NULL,
 porcentajeIN   NUMBER(3,0)     NOT NULL,   --  porcentaje del ahorro obligatorio invertido. Puede ser un 100% (inversión en un único fondo) o bien menos si se invierte en más de un fondo
 montoIN        NUMBER(9,0)     NOT NULL,   --  monto del ahorro obligatorio invertido. Puede ser la totalidad, si se prefirió 100%, o bien una parte si se distribuye en más de un fondo
 ejecutorIN     CHAR(2)         NOT NULL,   --  responsable de la inversión
 estadoIN       NUMBER(1,0)     NOT NULL
);

CREATE TABLE COMUNA
(codigoCM       NUMBER(5,0)   NOT NULL,
 nombreCM       VARCHAR2(50)  NOT NULL,
 codigoRG       NUMBER(2,0)   NOT NULL
);

CREATE TABLE AFP
(codigoAFP      NUMBER(4,0)    NOT NULL,
 nombreAFP      CHAR(13)       NOT NULL,
 comisionAFP    NUMBER(4,2)    NOT NULL
);


--  INTEGRIDAD DE ENTIDAD

ALTER TABLE COTIZANTE
ADD CONSTRAINT PK_COTIZANTE PRIMARY KEY(numeroCT);

ALTER TABLE INVERSION
ADD CONSTRAINT PK_INVERSION PRIMARY KEY(codigoIN, numeroIN);

ALTER TABLE COMUNA
ADD CONSTRAINT PK_COMUNA PRIMARY KEY(codigoCM);

ALTER TABLE AFP
ADD CONSTRAINT AFP PRIMARY KEY(codigoAFP);

--  INTEGRIDAD REFERENCIAL

ALTER TABLE COTIZANTE
ADD CONSTRAINT FK_COMUNA_COTIZANTE FOREIGN KEY(codigoCM)
REFERENCES COMUNA(codigoCM);

ALTER TABLE COTIZANTE
ADD CONSTRAINT PK_AFP_COTIZANTE FOREIGN KEY(codigoAFP)
REFERENCES AFP(codigoAFP);

ALTER TABLE INVERSION
ADD CONSTRAINT FK_COTIZANTE_INVERSION FOREIGN KEY(numeroCT)
REFERENCES COTIZANTE(numeroCT);

--  DATOS

INSERT INTO COMUNA VALUES (5101,'VALPARAISO',5);
INSERT INTO COMUNA VALUES (5102,'CASABLANCA',5);
INSERT INTO COMUNA VALUES (5103,'CONCON',5);
INSERT INTO COMUNA VALUES (5104,'JUAN FERNANDEZ',5);
INSERT INTO COMUNA VALUES (5105,'PUCHUNCAVI',5);
INSERT INTO COMUNA VALUES (5107,'QUINTERO',5);
INSERT INTO COMUNA VALUES (5109,'VIÑA DEL MAR',5);
INSERT INTO COMUNA VALUES (5201,'ISLA DE PASCUA',5);
INSERT INTO COMUNA VALUES (5301,'LOS ANDES',5);
INSERT INTO COMUNA VALUES (5302,'CALLE LARGA',5);
INSERT INTO COMUNA VALUES (5303,'RINCONADA',5);
INSERT INTO COMUNA VALUES (5304,'SAN ESTEBAN',5);
INSERT INTO COMUNA VALUES (5401,'LA LIGUA',5);
INSERT INTO COMUNA VALUES (5402,'CABILDO',5);
INSERT INTO COMUNA VALUES (5403,'PAPUDO',5);
INSERT INTO COMUNA VALUES (5404,'PETORCA',5);
INSERT INTO COMUNA VALUES (5405,'ZAPALLAR',5);
INSERT INTO COMUNA VALUES (5501,'QUILLOTA',5);
INSERT INTO COMUNA VALUES (5502,'CALERA',5);
INSERT INTO COMUNA VALUES (5503,'HIJUELAS',5);
INSERT INTO COMUNA VALUES (5504,'LA CRUZ',5);
INSERT INTO COMUNA VALUES (5506,'NOGALES',5);
INSERT INTO COMUNA VALUES (5601,'SAN ANTONIO',5);
INSERT INTO COMUNA VALUES (5602,'ALGARROBO',5);
INSERT INTO COMUNA VALUES (5603,'CARTAGENA',5);
INSERT INTO COMUNA VALUES (5604,'EL QUISCO',5);
INSERT INTO COMUNA VALUES (5605,'EL TABO',5);
INSERT INTO COMUNA VALUES (5606,'SANTO DOMINGO',5);
INSERT INTO COMUNA VALUES (5701,'SAN FELIPE',5);
INSERT INTO COMUNA VALUES (5702,'CATEMU',5);
INSERT INTO COMUNA VALUES (5703,'LLAILLAY',5);
INSERT INTO COMUNA VALUES (5704,'PANQUEHUE',5);
INSERT INTO COMUNA VALUES (5705,'PUTAENDO',5);
INSERT INTO COMUNA VALUES (5706,'SANTA MARIA',5);
INSERT INTO COMUNA VALUES (5801,'QUILPUE',5);
INSERT INTO COMUNA VALUES (5802,'LIMACHE',5);
INSERT INTO COMUNA VALUES (5803,'OLMUE',5);
INSERT INTO COMUNA VALUES (5804,'VILLA ALEMANA',5);
INSERT INTO COMUNA VALUES (6101,'RANCAGUA',6);
INSERT INTO COMUNA VALUES (6201,'SAN FERNANDO',6);

INSERT INTO AFP VALUES(1033,'AFP CAPITAL',1.44);
INSERT INTO AFP VALUES(1003,'AFP CUPRUM',1.44);
INSERT INTO AFP VALUES(1005,'AFP HABITAT',1.27);
INSERT INTO AFP VALUES(1008,'AFP PROVIDA',1.45);
INSERT INTO AFP VALUES(1032,'AFP PLANVITAL',1.16);
INSERT INTO AFP VALUES(1034,'AFP MODELO',0.77);
INSERT INTO AFP VALUES(1035,'AFP UNO',0.69);


