CREATE TABLE CREDITO_CUOTAS
(numeroCred   NUMBER(9,0)   NOT NULL,
 numeroCuota  NUMBER(2,0)   NOT NULL,
 montoCuota   NUMBER(6,0)   NOT NULL,
 fechaVenc    DATE          NOT NULL,
 fechaPago    DATE          NULL,
 estadoCuota  CHAR(1)       NOT NULL
);

ALTER TABLE CREDITO_CUOTAS ADD CONSTRAINT PK_CREDITO_CUOTAS PRIMARY KEY(numeroCred,numeroCuota);

ALTER TABLE CREDITO_CUOTAS ADD CONSTRAINT FK_CREDITO_CREDITO_CUOTAS FOREIGN KEY (numeroCred)
REFERENCES CREDITO(numeroCred);

